"""empty message

Revision ID: 2bd4918397d2
Revises: f93f39ae46e9
Create Date: 2023-08-14 16:20:21.499908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd4918397d2'
down_revision = 'f93f39ae46e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Destination', sa.String(length=120), nullable=True))
        batch_op.drop_column('country')
        batch_op.drop_column('territory_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('territory_state', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('Destination')

    # ### end Alembic commands ###
