"""empty message

Revision ID: 333b33a68c47
Revises: 154d1d89b45a
Create Date: 2023-08-15 17:34:35.191871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333b33a68c47'
down_revision = '154d1d89b45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['User_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('User_id')

    # ### end Alembic commands ###
